version: 2

updates:
  # Development tools
  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"

  - directory: "/"
    package-ecosystem: "npm"
    schedule:
      interval: "monthly"

  # Service dependencies
  - directory: "/packages/api"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "api"

  - directory: "/packages/bot"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "bot"

  - directory: "/packages/dashboard/"
    package-ecosystem: "npm"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "dashboard"

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "actions"
