version: 2

updates:
  # Development tools
  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"

  - directory: "/api"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[api]"

  - directory: "/bot"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[bot]"

  - directory: "frontend/"
    package-ecosystem: "npm"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[frontend]"

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[actions]"
