name = "frontend"
type = "webpack"
account_id = "6e8f81ce0e8ba25c184fa66b5fea3ac1"
workers_dev = false
route = "https://mousey.app/*"
zone_id = "f8de0f9058bde7873bba65185358924b"

[site]
bucket = "dist/"
entry-point = "worker"
