version: '3'

services:
  bot:
    build: ./bot
    command: python -m src
    depends_on:
      - db
      - redis
    volumes:
      - ./bot/:/app
    environment:
      - API_URL
      - API_TOKEN
      - BOT_TOKEN
      - PSQL_DSN
      - REDIS_URL
      - FERNET_KEY
      - SHARD_COUNT
      - JISHAKU_HIDE=true

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./data/bot/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    command: redis-server --loglevel warning
    volumes:
      - ./data/bot/redis:/data
