version: '3'

services:
  api:
    build: .
    command: uvicorn --host 0.0.0.0 --use-colors api:app
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./:/app

  bot:
    build: .
    command: python -m bot
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    environment:
      - BOT_TOKEN
      - PSQL_DSN
      - REDIS_URL
      - FERNET_KEY
      - JISHAKU_HIDE=true

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      # - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    # volumes:
    #   - ./data/redis:/data
